[project]
name = "ds-october-2026"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "your name", email = "reddytejaswi200@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "ipykernel>=6,<7",
    "jupyter>=1.1.1",
    "matplotlib>=3.11.2",
    "pandas>=3.0.6",
    "scikit-learn>=1.9.1",
    "seaborn>=0.13.2",
]

[project.scripts]
ds-october-2026 = "ds_october_2026:main"

[build-system]
requires = ["uv_build>=0.12.21,<0.13.0"]
build-backend = "uv_build"


